# Copyright "Towards ML-KEM & ML-DSA on OpenTitan" Authors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0


load("//rules:otbn.bzl", "otbn_binary", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "ntt_dilithium_4l",
    srcs = [
        "ntt_dilithium_4l.s",
    ],
)

otbn_library(
    name = "ntt_dilithium",
    srcs = [
        "ntt_dilithium.s",
    ],
)

otbn_library(
    name = "ntt_base_dilithium",
    srcs = [
        "ntt_base_dilithium.s",
    ],
)

otbn_library(
    name = "intt_dilithium",
    srcs = [
        "intt_dilithium.s",
    ],
)

otbn_library(
    name = "intt_base_dilithium",
    srcs = [
        "intt_base_dilithium.s",
    ],
)

otbn_library(
    name = "poly_pointwise_dilithium",
    srcs = [
        "poly_pointwise_dilithium.s",
    ],
)

otbn_library(
    name = "poly_pointwise_acc_dilithium",
    srcs = [
        "poly_pointwise_dilithium.s",
    ],
)

otbn_library(
    name = "poly_add_dilithium",
    srcs = [
        "poly_add_dilithium.s",
    ],
)

otbn_library(
    name = "poly_add_base_dilithium",
    srcs = [
        "poly_add_base_dilithium.s",
    ],
)

otbn_library(
    name = "poly_sub_dilithium",
    srcs = [
        "poly_sub_dilithium.s",
    ],
)

otbn_library(
    name = "key_pair_dilithium",
    srcs = [
        "key_pair_dilithium.s",
    ],
)

otbn_library(
    name = "key_pair_base_dilithium",
    srcs = [
        "key_pair_base_dilithium.s",
    ],
)

otbn_library(
    name = "key_pair_plain_dilithium",
    srcs = [
        "key_pair_plain_dilithium.s",
    ],
)

otbn_library(
    name = "verify_dilithium",
    srcs = [
        "verify_dilithium.s",
    ],
)

otbn_library(
    name = "verify_base_dilithium",
    srcs = [
        "verify_base_dilithium.s",
    ],
)

otbn_library(
    name = "verify_plain_dilithium",
    srcs = [
        "verify_plain_dilithium.s",
    ],
)

otbn_library(
    name = "poly_dilithium",
    srcs = [
        "poly_dilithium.s",
    ],
)

otbn_library(
    name = "poly_base_dilithium",
    srcs = [
        "poly_base_dilithium.s",
    ],
)

otbn_library(
    name = "poly_plain_dilithium",
    srcs = [
        "poly_plain_dilithium.s",
    ],
)

otbn_library(
    name = "rounding_dilithium",
    srcs = [
        "rounding_dilithium.s",
    ],
)

otbn_library(
    name = "sign_dilithium",
    srcs = [
        "sign_dilithium.s",
    ],
)

otbn_library(
    name = "sign_base_dilithium",
    srcs = [
        "sign_base_dilithium.s",
    ],
)

otbn_library(
    name = "sign_plain_dilithium",
    srcs = [
        "sign_plain_dilithium.s",
    ],
)
