//==================================================
// This file contains the Excluded objects
// Generated By User: unknown
// Format Version: 2
// Date: Thu Dec 18 20:45:41 2025
// ExclMode: default
//==================================================
CHECKSUM: "3569791575 3453920680"
INSTANCE: tb.dut
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_o.valid "logic kmac_data_o.valid"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_i.digest_share0 "logic kmac_data_i.digest_share0[383:0]"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_i.digest_share1 "logic kmac_data_i.digest_share1[383:0]"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_i.done "logic kmac_data_i.done"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_i.error "logic kmac_data_i.error"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_i.ready "logic kmac_data_i.ready"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_o.data "logic kmac_data_o.data[63:0]"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_o.hold "logic kmac_data_o.hold"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_o.next "logic kmac_data_o.next"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_o.last "logic kmac_data_o.last"
ANNOTATION: "[UNSUPPORTED]: standard OTBN does not use kmac interface"
Toggle kmac_data_o.strb "logic kmac_data_o.strb[7:0]"
