# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
# Modified by Authors of "Towards ML-KEM & ML-DSA on OpenTitan" (https://eprint.iacr.org/2024/1192).
# Copyright "Towards ML-KEM & ML-DSA on OpenTitan" Authors.

load("//rules:otbn.bzl", "otbn_binary", "otbn_consttime_test", "otbn_library", "otbn_sim_test")

package(default_visibility = ["//visibility:public"])

otbn_sim_test(
    name = "kyber512_mlkem_keypair_test",
    srcs = [
        "kyber512_mlkem_keypair_test.s",
    ],
    copts = ["-DKYBER_K=2"],
    dexp = "kyber512_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber512_mlkem",
        "//sw/otbn/crypto/mlkem:kyber512_packing",
        "//sw/otbn/crypto/mlkem:kyber512_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber512_mlkem_enc_test",
    srcs = [
        "kyber512_mlkem_enc_test.s",
    ],
    copts = ["-DKYBER_K=2"],
    dexp = "kyber512_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber512_mlkem",
        "//sw/otbn/crypto/mlkem:kyber512_packing",
        "//sw/otbn/crypto/mlkem:kyber512_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber512_mlkem_dec_test",
    srcs = [
        "kyber512_mlkem_dec_test.s",
    ],
    copts = ["-DKYBER_K=2"],
    dexp = "kyber512_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber512_mlkem",
        "//sw/otbn/crypto/mlkem:kyber512_packing",
        "//sw/otbn/crypto/mlkem:kyber512_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber512_mlkem_false_dec_test",
    srcs = [
        "kyber512_mlkem_false_dec_test.s",
    ],
    copts = ["-DKYBER_K=2"],
    dexp = "kyber512_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber512_mlkem",
        "//sw/otbn/crypto/mlkem:kyber512_packing",
        "//sw/otbn/crypto/mlkem:kyber512_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber768_mlkem_keypair_test",
    srcs = [
        "kyber768_mlkem_keypair_test.s",
    ],
    copts = ["-DKYBER_K=3"],
    dexp = "kyber768_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber768_mlkem",
        "//sw/otbn/crypto/mlkem:kyber768_packing",
        "//sw/otbn/crypto/mlkem:kyber768_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber768_mlkem_enc_test",
    srcs = [
        "kyber768_mlkem_enc_test.s",
    ],
    copts = ["-DKYBER_K=3"],
    dexp = "kyber768_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber768_mlkem",
        "//sw/otbn/crypto/mlkem:kyber768_packing",
        "//sw/otbn/crypto/mlkem:kyber768_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber768_mlkem_dec_test",
    srcs = [
        "kyber768_mlkem_dec_test.s",
    ],
    copts = ["-DKYBER_K=3"],
    dexp = "kyber768_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber768_mlkem",
        "//sw/otbn/crypto/mlkem:kyber768_packing",
        "//sw/otbn/crypto/mlkem:kyber768_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber768_mlkem_false_dec_test",
    srcs = [
        "kyber768_mlkem_false_dec_test.s",
    ],
    copts = ["-DKYBER_K=3"],
    dexp = "kyber768_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber768_mlkem",
        "//sw/otbn/crypto/mlkem:kyber768_packing",
        "//sw/otbn/crypto/mlkem:kyber768_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber1024_mlkem_keypair_test",
    srcs = [
        "kyber1024_mlkem_keypair_test.s",
    ],
    copts = ["-DKYBER_K=4"],
    dexp = "kyber1024_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber1024_mlkem",
        "//sw/otbn/crypto/mlkem:kyber1024_packing",
        "//sw/otbn/crypto/mlkem:kyber1024_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber1024_mlkem_enc_test",
    srcs = [
        "kyber1024_mlkem_enc_test.s",
    ],
    copts = ["-DKYBER_K=4"],
    dexp = "kyber1024_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber1024_mlkem",
        "//sw/otbn/crypto/mlkem:kyber1024_packing",
        "//sw/otbn/crypto/mlkem:kyber1024_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber1024_mlkem_dec_test",
    srcs = [
        "kyber1024_mlkem_dec_test.s",
    ],
    copts = ["-DKYBER_K=4"],
    dexp = "kyber1024_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber1024_mlkem",
        "//sw/otbn/crypto/mlkem:kyber1024_packing",
        "//sw/otbn/crypto/mlkem:kyber1024_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

otbn_sim_test(
    name = "kyber1024_mlkem_false_dec_test",
    srcs = [
        "kyber1024_mlkem_false_dec_test.s",
    ],
    copts = ["-DKYBER_K=4"],
    dexp = "kyber1024_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem:kyber1024_mlkem",
        "//sw/otbn/crypto/mlkem:kyber1024_packing",
        "//sw/otbn/crypto/mlkem:kyber1024_poly",
        "//sw/otbn/crypto/mlkem:kyber_basemul",
        "//sw/otbn/crypto/mlkem:kyber_cbd_isaext",
        "//sw/otbn/crypto/mlkem:kyber_intt",
        "//sw/otbn/crypto/mlkem:kyber_ntt",
        "//sw/otbn/crypto/mlkem:kyber_poly_gen_matrix",
    ],
)

# Refactor ML-KEM VER1

otbn_sim_test(
    name = "mlkem512_keypair_test_ver1",
    srcs = [
        "kyber512_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber512_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_keypair",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_encap_test_ver1",
    srcs = [
        "kyber512_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber512_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_decap_test_ver1",
    srcs = [
        "kyber512_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber512_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_decap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_false_decap_test_ver1",
    srcs = [
        "kyber512_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber512_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_decap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_keypair_test_ver1",
    srcs = [
        "kyber768_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber768_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_keypair",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_encap_test_ver1",
    srcs = [
        "kyber768_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber768_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_decap_test_ver1",
    srcs = [
        "kyber768_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber768_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_decap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_false_decap_test_ver1",
    srcs = [
        "kyber768_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber768_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_decap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_keypair_test_ver1",
    srcs = [
        "kyber1024_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber1024_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_keypair",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_encap_test_ver1",
    srcs = [
        "kyber1024_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber1024_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_decap_test_ver1",
    srcs = [
        "kyber1024_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber1024_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_decap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_false_decap_test_ver1",
    srcs = [
        "kyber1024_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=1",
    ],
    dexp = "kyber1024_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_decap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver1:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver1:basemul",
        "//sw/otbn/crypto/mlkem_ver1:cbd",
        "//sw/otbn/crypto/mlkem_ver1:intt",
        "//sw/otbn/crypto/mlkem_ver1:ntt",
        "//sw/otbn/crypto/mlkem_ver1:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver1:kmac_send_msg",
    ],
)

# Refactor ML-KEM VER2

otbn_sim_test(
    name = "mlkem512_keypair_test_ver2",
    srcs = [
        "kyber512_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber512_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_keypair",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_encap_test_ver2",
    srcs = [
        "kyber512_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber512_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_decap_test_ver2",
    srcs = [
        "kyber512_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber512_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_decap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_false_decap_test_ver2",
    srcs = [
        "kyber512_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber512_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_decap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_keypair_test_ver2",
    srcs = [
        "kyber768_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber768_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_keypair",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_encap_test_ver2",
    srcs = [
        "kyber768_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber768_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_decap_test_ver2",
    srcs = [
        "kyber768_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber768_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_decap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_false_decap_test_ver2",
    srcs = [
        "kyber768_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber768_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_decap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_keypair_test_ver2",
    srcs = [
        "kyber1024_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber1024_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_keypair",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_encap_test_ver2",
    srcs = [
        "kyber1024_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber1024_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_decap_test_ver2",
    srcs = [
        "kyber1024_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber1024_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_decap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_false_decap_test_ver2",
    srcs = [
        "kyber1024_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=2",
    ],
    dexp = "kyber1024_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_decap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver2:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver2:basemul",
        "//sw/otbn/crypto/mlkem_ver2:cbd",
        "//sw/otbn/crypto/mlkem_ver2:intt",
        "//sw/otbn/crypto/mlkem_ver2:ntt",
        "//sw/otbn/crypto/mlkem_ver2:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver2:kmac_send_msg",
    ],
)

# Refactor ML-KEM VER3

otbn_sim_test(
    name = "mlkem512_keypair_test_ver3",
    srcs = [
        "kyber512_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber512_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_keypair",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_encap_test_ver3",
    srcs = [
        "kyber512_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber512_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_decap_test_ver3",
    srcs = [
        "kyber512_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber512_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_decap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem512_false_decap_test_ver3",
    srcs = [
        "kyber512_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=2",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber512_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_decap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem512_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_keypair_test_ver3",
    srcs = [
        "kyber768_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber768_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_keypair",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_encap_test_ver3",
    srcs = [
        "kyber768_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber768_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_decap_test_ver3",
    srcs = [
        "kyber768_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber768_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_decap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem768_false_decap_test_ver3",
    srcs = [
        "kyber768_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=3",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber768_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_decap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem768_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_keypair_test_ver3",
    srcs = [
        "kyber1024_mlkem_keypair_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber1024_mlkem_keypair_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_keypair",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_encap_test_ver3",
    srcs = [
        "kyber1024_mlkem_enc_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber1024_mlkem_enc_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_decap_test_ver3",
    srcs = [
        "kyber1024_mlkem_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber1024_mlkem_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_decap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)

otbn_sim_test(
    name = "mlkem1024_false_decap_test_ver3",
    srcs = [
        "kyber1024_mlkem_false_dec_test.s",
    ],
    copts = [
        "-DKYBER_K=4",
        "--bnmulv_version_id=3",
    ],
    dexp = "kyber1024_mlkem_false_dec_test.dexp",
    deps = [
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_decap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_encap",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_keys",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_pack_ciphertext",
        "//sw/otbn/crypto/mlkem_ver3:mlkem1024_poly",
        "//sw/otbn/crypto/mlkem_ver3:basemul",
        "//sw/otbn/crypto/mlkem_ver3:cbd",
        "//sw/otbn/crypto/mlkem_ver3:intt",
        "//sw/otbn/crypto/mlkem_ver3:ntt",
        "//sw/otbn/crypto/mlkem_ver3:poly_gen_matrix",
        "//sw/otbn/crypto/mlkem_ver3:kmac_send_msg",
    ],
)
