# Auto-generated project tcl file


create_project lowrisc_ip_otbn_0.1 -force

set_property part xc7a200tfbg676-3 [current_project]




#set_property verilog_define {SYNTHESIS=1 BNMULV=1 } [get_filesets sources_1]
read_verilog -sv {../../../hw/ip/entropy_src/rtl/entropy_src_pkg.sv}
read_verilog -sv {../../../hw/ip/rv_dm/rtl/jtag_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_cipher_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_crc32.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_buf.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_flop.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_generic_flop_no_rst.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_xnor2.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_xor2.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_22_16_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_22_16_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_28_22_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_28_22_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_39_32_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_39_32_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_64_57_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_64_57_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_72_64_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_72_64_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sha2_pkg.sv}
read_verilog -sv {../../../hw/ip/prim_xilinx/rtl/prim_and2.sv}
read_verilog -sv {../../../hw/ip/prim_xilinx/rtl/prim_flop_en.sv}
read_verilog -sv {../../../hw/ip/prim_xilinx_ultrascale/rtl/prim_clock_inv.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_blanker.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_cdc_rand_delay.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_subst_perm.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_present.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_prince.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_count_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_count.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_clock_mux2.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_ram_1p.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_lfsr.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_dom_and_2share.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sec_anchor_buf.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sec_anchor_flop.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sha2_pad.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sha2.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sha2_32.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sparse_fsm_flop.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_util_pkg.sv}
read_verilog -sv {../../../hw/ip/prim_xilinx_ultrascale/rtl/prim_pad_wrapper.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_xoshiro256pp.sv}
read_verilog -sv {../../../hw/top_darjeeling/rtl/top_pkg.sv}
read_verilog -sv {../../../hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv}
read_verilog -sv {../../../hw/ip/prim_generic/rtl/prim_flop_2sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_leading_one_ppc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi4_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi4_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi4_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi8_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi8_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi8_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi12_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi12_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi12_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi16_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi16_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi16_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi20_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi20_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi20_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi24_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi24_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi24_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi28_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi28_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi28_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi32_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi32_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_mubi32_dec.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_onehot_enc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_onehot_mux.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_onehot_check.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_ram_1p_adv.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_arbiter_fixed.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_arbiter_ppc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_arbiter_tree.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_arbiter_tree_dup.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_diff_decode.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_fifo_async_simple.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_fifo_async.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_fifo_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_fifo_sync_cnt.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_ram_1p_scr.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_reg_we_check.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_rst_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_subreg_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_reg_cdc.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_reg_cdc_arb.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_subreg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_subreg_arb.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_subreg_ext.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_subreg_shadow.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_pkg.sv}
read_verilog -sv {../../../hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv}
read_verilog -sv {../../../hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_esc_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_esc_receiver.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_esc_sender.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_data_integ_enc.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_data_integ_dec.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv}
read_verilog -sv {../../../hw/ip/csrng/rtl/csrng_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/csrng/rtl/csrng_pkg.sv}
read_verilog -sv {../../../hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_alert_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_alert_receiver.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_alert_sender.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_lc_sync.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_fifo_sync.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_fifo_async.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_assert.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_err.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_assert_multiple.sv}
read_verilog -sv {../../../hw/ip/edn/rtl/edn_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/edn/rtl/edn_pkg.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_clock_gating_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sram_arbiter.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_slicer.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sync_reqack.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sync_reqack_data.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_sync_slow_fast.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_keccak.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_packer.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_packer_fifo.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_gate_gen.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_pulse_sync.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_filter.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_filter_ctr.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_intr_hw.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_reg.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_sram_byte.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_sram.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_lc_gate.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_request_loopback.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_err_resp.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_socket_1n.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_socket_m1.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/sram2tlul.sv}
read_verilog -sv {../../../hw/ip/keymgr/rtl/keymgr_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/keymgr/rtl/keymgr_pkg.sv}
read_verilog -sv {../../../hw/ip/prim/rtl/prim_edn_req.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_host.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_racl.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dm_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dm_sba.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dm_mem.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dmi_cdc.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv}
read_verilog -sv {../../../hw/vendor/pulp_riscv_dbg/src/dm_top.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_dmi.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv}
read_verilog -sv {../../../hw/ip/tlul/rtl/tlul_jtag_dtm.sv}
read_verilog -sv {../../../hw/ip/kmac/rtl/sha3_pkg.sv}
read_verilog -sv {../../../hw/ip/kmac/rtl/keccak_round.sv}
read_verilog -sv {../../../hw/ip/kmac/rtl/keccak_2share.sv}
read_verilog -sv {../../../hw/ip/kmac/rtl/sha3pad.sv}
read_verilog -sv {../../../hw/ip/kmac/rtl/sha3.sv}
read_verilog -sv {../../../hw/ip/kmac/rtl/kmac_pkg.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_controller.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_decoder.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_predecode.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_instruction_fetch.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rf_base.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rf_bignum.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rf_base_ff.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rf_bignum_ff.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rf_base_fpga.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rf_bignum_fpga.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_lsu.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_alu_base.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_alu_bignum.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_mac_bignum.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/bn_vec_core/unified_mul.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/bn_vec_core/buffer_bit_double.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_loop_controller.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_stack.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_rnd.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_start_stop_control.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_core.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_reg_top.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn_scramble_ctrl.sv}
read_verilog -sv {../../../hw/ip/otbn/rtl/otbn.sv}
read_verilog -sv {/tmp/wrapper.sv}

set_property include_dirs [list ../../../hw/ip/prim/rtl .] [get_filesets sources_1]
set_property top wrapper [current_fileset]
set_property source_mgmt_mode None [current_project]


