load("//rules:otbn.bzl", "otbn_binary")

package(default_visibility = ["//visibility:public"])

otbn_binary(
    name = "bnmulv8S_smoke_test",
    srcs = [
        "bnmulv8S_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=1"],
)

otbn_binary(
    name = "bnmulv16H_smoke_test",
    srcs = [
        "bnmulv16H_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=1"],
)

otbn_binary(
    name = "bnmulvl8S_smoke_test",
    srcs = [
        "bnmulvl8S_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=1"],
)

otbn_binary(
    name = "bnmulvl16H_smoke_test",
    srcs = [
        "bnmulvl16H_smoke_test.s",
    ],
    copts = ["--bnmulv_version_id=1"],
)
